# Generated by Django 5.1.15 on 2026-01-19 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedal',
            name='default_settings',
        ),
        migrations.AddField(
            model_name='amplifier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='amplifier',
            name='form_factor',
            field=models.CharField(choices=[('HEAD', 'Head'), ('COMBO', 'Combo'), ('RACK', 'Rackmount'), ('PEDAL', 'Pedal Amp')], default='HEAD', max_length=20),
        ),
        migrations.AddField(
            model_name='amplifier',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amplifier',
            name='num_channels',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='guitar',
            name='body_shape',
            field=models.CharField(choices=[('STRAT', 'Stratocaster Style'), ('TELE', 'Telecaster Style'), ('LP', 'Les Paul Style'), ('SG', 'SG Style'), ('OFFSET', 'Offset (Jazzmaster/Jaguar)'), ('SUPERSTRAT', 'Superstrat'), ('HOLLOW', 'Hollow Body / Semi-Hollow'), ('DREADNOUGHT', 'Dreadnought'), ('CUTAWAY', 'Acoustic with Cutaway'), ('PARLOR', 'Parlor / Folk'), ('CLASSICAL_SHAPE', 'Classical Shape'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='guitar',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guitar',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownedgear',
            name='user_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pedal',
            name='bypass_type',
            field=models.CharField(choices=[('TRUE', 'True Bypass'), ('BUFFERED', 'Buffered'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='pedal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedal',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amplifier',
            name='amp_type',
            field=models.CharField(choices=[('TUBE', 'Tube (Valve)'), ('SOLID_STATE', 'Solid State'), ('DIGITAL', 'Digital/Modeling'), ('HYBRID', 'Hybrid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='guitar_type',
            field=models.CharField(choices=[('ELECTRIC', 'Electric Guitar'), ('ELECTRO_ACOUSTIC', 'Electro-Acoustic Guitar'), ('BASS', 'Bass Guitar'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='pickup_config',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ownedgear',
            name='nickname',
            field=models.CharField(blank=True, help_text="e.g. 'My Old Strat'", max_length=100),
        ),
        migrations.AlterField(
            model_name='ownedgear',
            name='notes',
            field=models.TextField(blank=True, help_text='Modifications, history, etc.'),
        ),
        migrations.AlterField(
            model_name='pedal',
            name='pedal_type',
            field=models.CharField(choices=[('OVERDRIVE', 'Overdrive'), ('DISTORTION', 'Distortion'), ('FUZZ', 'Fuzz'), ('BOOST', 'Boost'), ('DELAY', 'Delay'), ('REVERB', 'Reverb'), ('MODULATION', 'Modulation (Chorus/Phaser/Flanger)'), ('COMPRESSOR', 'Compressor'), ('TUNER', 'Tuner'), ('MULTI', 'Multi-Effects'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='ownedgear',
            index=models.Index(fields=['user', 'is_favorite'], name='equipment_o_user_id_7b216a_idx'),
        ),
    ]
